import img1 from "./assets/1.jpg"
import img2 from "./assets/2.jpg"
import img3 from "./assets/3.jpg"
import img4 from "./assets/4.jpg"
import img5 from "./assets/5.png"
import img6 from "./assets/6.jpg"
import img7 from "./assets/7.png"
import img8 from "./assets/8.jpg"
import img9 from "./assets/9.jpg"
import img10 from "./assets/10.jpg"
import img11 from "./assets/11.jpg"
import img12 from "./assets/12.jpg"
import img13 from "./assets/13.jpg"
import img14 from "./assets/14.jpg"
import img15 from "./assets/15.jpg"
import img16 from "./assets/16.jpg"
import img17 from "./assets/17.png"
import img18 from "./assets/18.jpg"
import img19 from "./assets/19.jpg"
import img20 from "./assets/20.png"
import img21 from "./assets/21.jpg"
import img22 from "./assets/22.png"

 const data = [
{
 id: 1 ,
 name: "La Roche-Posay Toleriane Hydrating Gentle Cleanser 400ML",
 img:img1,
 description:"A milky cream cleanser that hydrates skin.",
 price:16,
 overview:"La Roche-Posay Hydrating Gentle Soap Free Cleanser is a daily face wash for normal to dry skin. This cream cleanser gently rids skin of makeup, dirt and impurities, while maintaining skin's natural moisture barrier and pH. A gentle formula helps to restore skin comfort and retains essential moisture, leaving skin feeling comfortable and hydrated." ,
 use : "Use as a daily face wash for normal to dry skin to remove makeup, dirt, impurities, and hydrate skin. Cleanse morning and/or evening. Wet skin with lukewarm water. Pump cleanser into hands and work into lather. Massage into skin in a gentle, circular motion. Rinse thoroughly and pat dry without rubbing.",
 ingredients: "Aqua/Water/Eau, Glycerin, Pentaerythrityl Tetraethylhexanoate, Propanediol, Ammonium Polyacryloyldimethyl Taurate, Polysorbate 60, Ceramide Np, Niacinamide, Sodium Chloride, Coco-Betaine, Disodium Edta Caprylyl Glycol, Panthenol, Tocopherol (Code Fil: D242855/1)",
 category: "cleanser",
},
{
 id:2,
 name:"SENTÉ Daily Soothing Cleanser 163ML",
 img:img3,
 description:"A gentle facial cleanser for dry and sensitive skin types.",
 price:34,
 overview:"Refresh your skin day and night with Daily Soothing Cleanser from Sente Labs. Formulated for even the most sensitive skin types, this gentle face cleanser washes away makeup and impurities without irritating the skin. Herbal extracts replenish hydration resulting in a softer and smoother complexion.",
 use :"Apply cleanser onto the fingertips, add water and gently cleanse the face using circular motion. Rinse thoroughly with water. Use daily morning and night or as advised by your skincare professional.",
 ingredients:"Water (Aqua), Triheptanoin, Glycerin, Ricinus Communis (Castor) Seed Oil, Di-PPG-2 Myreth-10 Adipate, Dimethicone, Coco-Glucoside, Glyceryl Oleate, Cetearyl Alcohol, Behenyl Alcohol, Glyceryl Stearate, Ophiopogon Japonicus Root Extract, Physalis Pubescens Fruit Juice, Rhus Verniciflua Peel Wax/Rhus Succedanea Fruit Wax, Lecithin, Hydrolyzed Caesalpinia Spinosa Gum, Caesalpinia Spinosa Gum, Caprylic/Capric Triglyceride, Glycine Soja (Soybean) Sterols, Hydroxyacetophenone, Polyacrylate-13, Polyisobutene, Polysorbate 20, Aminomethyl Propanol, Xanthan Gum, Tocopherol, Ascorbyl Palmitate, Ethylhexylglycerin, Phenoxyethanol, Disodium EDTA.",
 category: "cleanser",
},
{
 id:3,
 name:"La Roche-Posay Toleriane Purifying Foaming Cleanser 400ML",
 img:img4,
 description:"A radiance-boosting face wash for all skin types.",
 price:16,
 overview:"Wash the day away from normal, sensitive and oily skin with La Roche-Posay's high-quality Toleriane Purifying Foaming Soap Free Cleanser. Its formula incorporates powerful antioxidants and ceramides to alleviate free radical damage and oiliness. This face wash is oil-free, sulfate-free and fragrance-free." ,
 use :"Use as a daily face wash for normal to oily skin to remove makeup, dirt, impurities, and excess oil. Cleanse morning and/or evening. Wet skin with lukewarm water. Pump cleanser into hands and work into lather. Massage into skin in a gentle, circular motion. Rinse thoroughly and pat dry without rubbing.",
 ingredients:"Aqua/Water/Eau, Glycerin, Coco-Betaine, Propanediol, Sodium Cocoyl Glycinate, Peg-120 Methyl Glucose Dioleate, Sodium Chloride, Sodium Hydroxide, Citric Acid, Ceramide Np, Niacinamide Disodium Edta, Capryloyl Glycine, Caprylyl Glycol, Acrylates Copolymer (Code Fil: D240552/1)",
 category:"cleanser",
},
{
 id: 4,
 name:"SkinMedica TNS Advanced+ Serum",
 img:img11,
 description:"A powerful anti-aging serum that targets fine lines, deep wrinkles and sagging skin.",
 price:295,
 overview:"SkinMedica's TNS Advanced+ Serum is a skin rejuvenating formula that visibly improves the appearance of coarse wrinkles, fine lines and sagging skin. Powered by TNS®-MR and Renessensce (RSC) Advanced, this combination encourages skin cell renewal and supports collagen and elastin levels revealing a smoother, more radiant and youthful complexion." ,
 use :"AM/PM: Dispense a single pump onto the back of your hand, blend together and apply to the face morning and night. Avoid getting in eyes. If contact occurs, rinse eyes thoroughly with water.",
 ingredients:"Water/Aqua/Eau, Pentylene Glycol, Human Fibroblast Conditioned Media, Glycereth-7 Triacetate, Shea Butter Ethyl Esters, Glycerin, Ethoxydiglycol, Lactococcus Ferment Lysate, Whey Protein, Chlorella Vulgaris Extract, Saccharide Isomerate, Trifluoroacetyl Tripeptide-2, Dimer Tripeptide-43, Hydrolyzed Linseed Extract, Vitis Vinifera (Grape) Flower Cell Extract, Pyrus Malus (Apple) Fruit Extract, Hydroxyacetophenone, Tocopheryl Acetate, Propanediol, Xanthan Gum, Polyacrylate Crosspolymer-6, Polyacrylate-13, Polyisobutene, Sclerotium Gum, PEG-12 Dimethicone, Lecithin, Pullulan, Butylene Glycol, Sodium Citrate, Polysorbate 20, Aminomethyl Propanol, Dextran, Disodium EDTA, Phenoxyethanol, Ethylhexylglycerin.",
 category:"serums",
},
{
 id:5,
 name:"Osmosis +Beauty Deep Clean Detox Cleanser 200ML",
 img:img6,
 description:"A radiance-boosting face wash for all skin types.",
 price:44,
 overview:"Embark on an invigorating clean with our unique blend of citrus essential oils and coconut. Let this gentle yet effective cleanser remove deep impurities, leaving your skin refreshed and revitalized. Suitable for all skin types, it's the ultimate detoxifying experience." ,
 use :"Gently massage one pump onto damp skin and rinse thoroughly.",
 ingredients:"Water, Glycerin, Sodium Coco-Glucoside Tartrate, Cocamidopropyl Hydroxysultaine, Sodium Hydroxypropylsulfonate Laurylglucoside Crosspolymer, Sodium Cocoamphoacetate, Sodium Cocoyl Hydrolyzed Amaranth Protein, Lauryl Glucoside, Sodium Methyl Cocoyl Taurate, Leuconostoc/Radish Root Ferment Filtrate, Citrus Sinensis (Orange) Fruit Extract, Cymbopogon Schoenanthus Oil, Santalum Austrocaledonicum Wood Oil, Citrus Limon (Lemon) Peel Oil, Citrus Grandis (Grapefruit) Peel Oil, Citrus Aurantium Dulcis (Orange) Peel Oil, Sodium Hydroxypropylsulfonate Decylglucoside Crosspolymer, Sodium Cocoyl Glutamate, Sodium Lauryl Glucose Carboxylate, Sodium Gluconate, Caprylhydroxamic Acid, Benzyl Alcohol.",
 category:"cleanser",
},
{
 id:6,
 name:"La Roche-Posay Toleriane Double Repair Moisturizer",
 img:img15,
 description:"A daily face moisturizer that deeply hydrates and soothes skin.",
 price:23,
 overview:"Soothe and comfort your skin every day with La Roche-Posay's Double Repair Face Moisturizer. Suitable for sensitive skin types, this facial moisturizer is powered by prebiotic thermal water that helps diminish dryness and free radical damage for a more youthful, healthier-looking complexion." ,
 use :"Use as a daily facial moisturizer to hydrate and soothe skin. Apply to the face and neck morning and/or evening. Its soft, oil-free texture is easily absorbed.",
 ingredients:"Aqua/water (la roche-posay prebiotic thermal water), glycerin, dimethicone, hydrogenated polyisobutene, niacinamide, ammonium, polyacryloyldimethyl taurate, myristyl myristate, stearic acid, ceramide np, potassium cetyl phosphate, isobutane, glyceryl stearate se, sodium hydroxide, myristic acid, palmitic acid, capryloyl glycine, caprylyl glycol, xanthan gum, t-butyl alcohol, acrylonitrile/methyl methacrylate/vinylidene chloride copolymer, tocopherol.",
 category:"moisturizers",
},
{
 id:7,
 name:"CeraVe Hydrating Facial Cleanser 355ML",
 img:img7,
 description:"A replenishing and fortifying cleanser that helps reinforce the skin's barrier.",
 price:16,
 overview:"CeraVe Hydrating Facial Cleanser gently washes away makeup, dirt, excess oil and impurities without drying out the skin. Ceramides hydrate and repair the skin barrier as nurturing ingredients moisturize. A patented delivery technology releases these ingredients over time, for an immediate and long-term effect. Skin is left fresh and clean, without any oily residue or tight feeling left behind. Ideal for normal to dry skin types." ,
 use :"Wet skin with lukewarm water and massage cleanser into skin in a gentle, circular motion. Rinse and gently pat skin until dry.",
 ingredients:"Aqua / Water / Eau, Glycerin, Cetearyl Alcohol, Peg-40 Stearate, Stearyl Alcohol, Potassium Phosphate, Ceramide Np, Ceramide Ap, Ceramide Eop, Carbomer, Glyceryl Stearate, Behentrimonium Methosulfate, Sodium Lauroyl Lactylate, Sodium Hyaluronate, Cholesterol, Phenoxyethanol, Disodium Edta, Dipotassium Phosphate, Tocopherol, Phytosphingosine, Xanthan Gum, Cetyl Alcohol, Polysorbate 20, Ethylhexylglycerin.",
 category:"cleanser",
},
{
 id:8,
 name:"La Roche-Posay Hyalu B5 Hyaluronic Acid Serum",
 img:img14,
 description:"A highly concentrated serum that improves the skin's tone and texture. ",
 price:40,
 overview:"Hyalu B5 Hyaluronic Acid Serum and Anti-Aging Concentrate is a serum formulated with two types of Hyaluronic Acid and Vitamin B5. With high molecular weight Hyaluronic Acid and low molecular weight Hyaluronic Acid, Hyalu B5 helps lock in moisture and leaves skin feeling plump to the touch. Also formulated with Vitamin B5 Hyalu B5 helps repair skin's natural moisture barrier to help skin retain hydration. This Hyaluronic Acid serum has a fresh fragrance in an allergy tested formula and also contains, Madecassoside and La Roche-Posay Thermal Spring Water to help soothe skin. Use as a daily anti-aging and Hyaluronic Acid serum to visibly plump, hydrate, and help reduce signs of aging. Apply facial serum morning and/or evening to the face and neck. Use alone or as an added boost to your favorite moisturizer. Rich serum texture leaves skin feeling supple and hydrated to the touch." ,
 use :"After cleansing, apply face serum morning and/or evening to the face and neck. Rich serum texture leaves skin feeling supple and hydrated to the touch. Can be used alone or under a moisturizer.",
 ingredients:"Aqua / Water, Glycerin, Alcohol Denat, Propylene Glycol, Panthenol, Pentylene Glycol, Dimethicone, Peg-6 Caprylic/Capric Glycerides, Ppg-6-Decyltetradeceth-30, Glyceryl Isostearate, Madecassoside, Sodium Hyaluronate, Ammonium Polyacryloyldimethyl Taurate, Disodium Edta, Hydrolyzed Hyaluronic Acid, Caprylyl Glycol, Citric Acid, Xanthan Gum, Butylene Glycol, Tocopherol, Phenoxyethanol, Parfum / Fragrance",
 category:"serums",
},
{
 id:9,
 name:"COSRX Low PH Good Morning Gel Cleanser 150ML",
 img:img8,
 description:"A resurfacing serum that renews skin and reduces the look of whiteheads.",
 price:14,
 overview:"Dreaming of a tighter, more luminous complexion? Make that dream a reality with Low PH Good Morning Gel Cleanser from COSRX. Crafted with tea tree and beta hydroxy acids, this mild cleanser works to reduce the look of large pores and helps control oil production." ,
 use :"Gently massage a small amount of Low pH Good Morning Gel Cleanser on wet skin. Rinse with tepid water. Pat your face dry, and continue with your next skin care steps.",
 ingredients:"Water, Cocamidopropyl Betaine, Sodium Lauroyl Methyl Isethionate, Polysorbate 20, Styrax Japonicus Branch/Fruit/Leaf Extract, Butylene Glycol, Saccharomyces Ferment, Cryptomeria Japonica Leaf Extract, Nelumbo Nucifera Leaf Extract, Pinus Palustris Leaf Extract, Ulmus Davidiana Root Extract, Oenothera Biennis (Evening Primrose) Flower Extract, Pueraria Lobata Root Extract, Melaleuca Alternifolia (Tea Tree) Leaf Oil, Allantoin, Caprylyl Glycol, Ethylhexylglycerin, Betaine Salicylate, Citric Acid, Ethyl Hexanediol, 1,2-Hexanediol, Trisodium Ethylenediamine Disuccinate, Sodium Benzoate, Disodium EDTA",
 category:"cleanser",
},
{
 id:10,
 name:"Colorescience Sunforgettable® Total Protection™ Sport Stick SPF 50",
 img:img21,
 description:"A water-resistant SPF stick that protects the skin from environmental damage.",
 price:34,
 overview:"Sunforgettable® Total Protection™ Sport Stick SPF 50 from Colorescience provides powerful and convenient sun protection. Designed with EnviroScreen™ Technology, it delivers all-mineral protection from environmental aggressors, such as UVA/UVB, pollution, blue light and infrared radiation. Patented ingredients in an antioxidant-rich mineral formula protect against free radicals that contribute to skin damage while jojoba esters and squalane provide nourishing hydration to soften and smooth skin texture. Perfect for sunny days on the field, court, or playground, get on-the-go application and powerful protection for outdoor activities with 100% chemical-free mineral actives and gentle ingredients and a sheer, elegant, dry-touch finish." ,
 use :"Glide liberally onto skin and blend with fingertips for even coverage and a sheer, dry-touch finish. Reapply at least every two hours.",
 ingredients:"Squalane, Jojoba Esters, Euphorbia Cerifera (Candelilla) Wax, Nylon-12, C12-15 Alkyl Benzoate, Butyloctyl Salicylate, Glyceryl Dibehenate, Polymethylsilsesquiox-ane, Hydrogenated Coco-Glycerides, Poly C10-30 Alkyl Acrylate, Dimethiconol/Propylsilsesquioxane/Silicate Crosspolymer, Methylpropanediol, Tridecyl Salicylate, Tribehenin, C26-28 Alkyl Dimethicone, Synthetic Wax, Glyceryl Behenate, Triceteareth-4 Phosphate, Capryly Glycol, Physalis Angulata Extract, Caprylic/Capric Triglyceride, Bisabolol, Phenylpropanol, Dimethylmethoxy,Chromanol, Tocopheryl Acetate,Tocopherol, Dimethicone, Iron Oxides CI77492.",
 category:"spf",
},
{
 id:11,
 name:"Sanitas Skincare Lemon Cream Scrub 115ML",
 img:img9,
 description:"An exfoliating scrub that buffs away dead skin cells to reveal smooth, radiant skin.",
 price:34,
 overview:"Sanitas Skincare Lemon Cream Scrub gently exfoliates dead skin cells, impurities and excess oil without causing dryness or irritation. Jojoba oil softens skin and helps maintain your skin's natural lipid barrier. Hyaluronic acid imparts light hydration, while vitamins C and E work together to strengthen your skin's ability to defend itself from environmental aggressors." ,
 use :"Apply 1-2 pumps to fingertips and using a circular motion, gently massage onto damp skin. Rinse well and use up to 3 times a week.",
 ingredients:"Water/Aqua/Eau, Decyl Glucoside, Simmondsia Chinensis (Jojoba) Seed Oil, Hydrated Silica, Polyacrylamide, Citrus Limon (Lemon) Peel Oil, C13-14 Isoparaffin, Astrocaryum Murumuru Seed Butter, Theobroma Grandiflorum (Cupuau) Seed Butter, Santalum Album (Sandalwood) Extract, Phellodendron Amurense Bark Extract, Phospholipids, Lecithin, Hordeum Vulgare (Barley) Extract/Hordeum Vulgare/Extrait D'orge, Tocopheryl Acetate (Vitamin E), Tetrahexyldecyl Ascorbate (Vitamin C), Sodium Hyaluronate (Hyaluronic Acid), Pca Dimethicone, Laureth-7, Polysorbate 80, Glycerin, Alcohol, Palm Alcohol, Phytosteryl Canolate, Lactic Acid, Ethylhexylglycerin, Methylpropanediol, Caprylhydroxamic Acid.",
 category:"cleanser",
},
{
 id:12,
 name:"Paula's Choice Omega Complex Cleansing Balm 103ML",
 img:img10,
 description:"A fragrance-free cleansing balm to deeply cleanse and soften skin.",
 price:29,
 overview:"The Omega+ Complex Cleansing Balm from Paula's Choice is a triple-action balm rich in omegas 3, 6 and 9 to thoroughly cleanse and noticeably soften skin. This fragrance-free cleansing balm melts into the skin to effortlessly dissolve stubborn makeup and sunscreen while rinsing away without leaving any residue. Its barrier-repairing complex of coconut-derived fatty acids plus omega-rich jojoba oil conditions skin while preventing moisture loss during cleansing." ,
 use :"Gently massage a small amount onto wet or dry skin. Rinse well with warm water. For a deeper clean, leave on for 60 seconds then remove with a soft washcloth.",
 ingredients:"Ethylhexyl Palmitate, Caprylic/Capric Triglyceride, PEG-20 Glyceryl Triisostearate, Diisooctyl Succinate, Olive Oil PEG-7 Esters, Trihydroxystearin, Glyceryl Stearate, Limnanthes Alba (Meadowfoam) Seed Oil, Simmondsia Chinensis (Jojoba) Seed Oil, Hydrogenated Rapeseed Oil, Tocopheryl Acetate",
 category:"cleanser",
},
{
 id:13,
 name:"iS Clinical Hydra-Cool Serum",
 img:img12,
 description:"A multi-use formula to restore hydration and provide excellent antioxidant protection.",
 price:96,
 overview:"Hydra-Cool Serum contains the powerful, healing antioxidant centella asiatica with vitamin B5, hyaluronic acid, kojic acid and soothing menthol. It works to hydrate and nourish the skin while providing intense protection through antioxidants. Ideal for all ages and all skin types, including sensitive, just-sunburned skin." ,
 use :"Apply sparingly to clean skin, smoothing over face and neck (or as directed). Serum may be used by itself or layered with other iS Clinical products. For best results, follow complete iS Clinical regimen.",
 ingredients:"Water/Aqua/Eau, Sodium Hyaluronate, Pantothenic Acid, Pentylene Glycol, Menthol, Phenoxyethanol, Asiaticoside, Polyporus Umbellatus (Mushroom) Extract, Asiatic Acid, Madecassic Acid, Blue 1 (CI 42090)",
 category:"serums",
},
{
 id:14,
 name:"Paula's Choice CLINICAL Niacinamide 20% Treatment",
 img:img13,
 description:"A highly concentrated serum that improves the skin's tone and texture. ",
 price:52,
 overview:"Achieve a smoother and more radiant complexion with CLINICAL Niacinamide 20% Treatment from Paula's Choice. This advanced, concentrated serum helps to tighten and minimize the appearance of pores and rough bumps caused by age or sun damage. Niacinamide normalizes pore function and protects from further stretching when exposed to damaging UV light, resulting in improved radiance and texture." ,
 use :"Apply a few drops once or twice daily after cleansing, toning and exfoliating. At night, layer with other treatment products as needed and follow with moisturizer; during the day, finish with a sunscreen rated SPF 30 or greater.",
 ingredients:"Water (Aqua), Niacinamide, Pentylene Glycol, Butylene Glycol, Glycerin, Acetyl Glucosamine, Ascorbyl Glucoside, Glycyrrhiza Glabra (Licorice) Root Extract, Spiraea Ulmaria (Meadowsweet) Extract, Portulaca Oleracea (Purslane) Extract, Camellia Japonica Flower Extract, Epigallocatechin Gallate, Boerhavia Diffusa Root Extract, Camellia Sinensis (Green Tea) Leaf Extract, Allantoin, Lecithin, Pullulan, Panthenol, Silica, Xanthan Gum, Sclerotium Gum, Propanediol, Sodium Phytate, Phenoxyethanol, Ethylhexylglycerin.",
 category:"serums",
},
{
 id:15,
 name:"SkinCeuticals Antioxidant Lip Repair",
 img:img22,
 description:"A rejuvenating lip treatment with antioxidants.",
 price:46,
 overview:"SkinCeuticals Antioxidant Lip Repair prevents premature aging while restoring moisture and smoothing the surface of the lips. It uses two powerful antioxidants, silymarin and vitamin E, to shield the delicate lip area from the ravages of sun, smoke and air damage. Special botanical emollients hydrate and heal while an AHA-free exfoliating complex softens and smooths the texture of your lips" ,
 use :"Once or twice daily after cleansing, massage a small amount into dry lips.",
 ingredients:"Aqua / Water / Eau, Hydrogenated Polyisobutene, Glycerin, Cera Microcristallina / Microcrystalline Wax / Cire Microcristalline, Dimethicone, Undecane, Tridecane, Peg/Ppg-18/18 Dimethicone, Silica, Alcohol Denat., Tocopheryl Acetate, Polymethylsilsesquioxane, Ethylhexyl Palmitate, Phenoxyethanol, Lauryl Peg-9 Polydimethylsiloxyethyl Dimethicone, Tocopherol, Magnesium Sulfate, Disteardimonium Hectorite, Glucosamine Hcl, Tribehenin, Caprylyl Glycol, Allantoin, Disodium Edta, Hydroxyethyl Urea, Sorbitan Isostearate, Sodium Hyaluronate, Faex Extract / Yeast Extract / Extrait De Levure, Biosaccharide Gum-1, Palmitoyl Oligopeptide, Silybum Marianum Extract.",
 category:"lipcare",
},
{
 id:16,
 name:"Dr. Loretta Gentle Hydrating Cleanser 200ML",
 img:img5,
 description:"A sulfate-free cleanser that removes makeup and impurities.",
 price:35,
 overview:"Wash the day away with Dr. Loretta's Gentle Hydrating Cleanser. Crafted with a sulfate-free formula, this calming cleanser removes makeup and impurities without stripping the skin of any natural oils. Suitable for normal to dry, sensitive and post-procedure skin." ,
 use :"Massage onto wet skin. Rinse off with 10 splashes of lukewarm water. Follow with a Dr. Loretta serum. Use AM and PM. Can be used post-procedure.",
 ingredients:"Water (Aqua), Sodium Cocoyl Wheat Amino Acids, Cocamidopropyl Betaine, Glycerin, Hydroxypropyl Guar, Ahnfeltiopsis Concinna (Red Algae) Extract, Hydrolyzed Algin, Anthemis Nobilis (Chamomile) Flower Oil, Zingiber Officinale (Ginger) Oil, Phenoxyethanol.",
 category:"cleanser",
},
{
 id:17,
 name:"Caudalie Premier Cru Skin Barrier Rich Moisturizer with Bio-Ceramides",
 img:img16,
 description:"A rich anti-aging moisturizer that visibly repairs skin barrier.",
 price:129,
 overview:"This luxurious deeply nourishing moisturizer replenishes the dry skin's moisture barrier with Bio-ceramides, while targeting the 8 signs of aging. Clinically shown to visibly improve elasticity, firmness, wrinkles, dark spots, plumpness, hydration, and radiance with the breakthrough TET8™ patent." ,
 use :"Apply Premier Cru The Rich Cream morning and evening, on the face and neck, alone or after your serum. Premier Cru The Rich Cream is refillable: once finished, remember to keep your jar and only throw away the empty refill",
 ingredients:"Aqua/Water/Eau, Glycerin, Caprylic/Capric Triglyceride, Vitis Vinifera (Grape) Seed Oil, Hydrogenated Ethylhexyl Olivate, Butyrospermum Parkii (Shea) Butter Extract, Cetearyl Alcohol, Butylene Glycol, Cetearyl Glucoside, Propanediol, Palmitoyl Grapevine Shoot Extract, Palmitoyl Grape Seed Extract, Hydrogenated Olive Oil Unsaponifiables, Pentaerythrityl Distearate, Potassium Cetyl Phosphate, Carbomer, Caprylyl Glycol, Ceramide Np, Xanthan Gum, Ci 77891 (Titanium Dioxide), Hydrolyzed Hyaluronic Acid, Magnolia Grandiflora Bark Extract, Potassium Sorbate, Tocopherol, Helianthus Annuus (Sunflower) Seed Oil, Adenosine, Sodium Hydroxide, Sodium Phytate, Geraniol, Linalool, Ci 77491 (Iron Oxides), Paeonia Lactiflora Root Extract, Ci 77492 (Iron Oxides), Sodium Citrate, Parfum (Fragrance), Citronellol.(315/011)",
 category:"moisturizers",
},
{
 id:18,
 name:"Paula's Choice Skincare C5 Super Boost Moisturizer",
 img:img17,
 description:"A concentrated 5% vitamin C moisturizer",
 price:45,
 overview:"This multifaceted vitamin C moisturizer evens tone and boosts firmness while preventing further signs of aging caused by free-radical damage. An innovative blend of peptides and polyglutamic acid strengthens skin's barrier and locks in hydration for up to 24 hours." ,
 use :"Use once or twice daily after cleansing, toning and exfoliating. Apply a dime-sized amount to face and neck. For daytime, always finish with SPF 30+.",
 ingredients:"Water/Aqua/Eau, Dicaprylyl Carbonate, 3-O-Ethyl Ascorbic Acid, Dimethicone, Butylene Glycol, Polyglyceryl-6 Distearate, Ascorbyl Glucoside, Squalane, Hydroxyethyl Acrylate/Sodium Acryloyldimethyl Taurate Copolymer, Acetyl sh-Hexapeptide-5 Amide Acetate, Citrullus Lanatus (Watermelon) Seed Oil, Hydrogenated Lecithin, Theobroma Cacao (Cocoa) Seed Butter, Hydrogenated Phosphatidylcholine, Pentaerythrityl Tetra-di-t-butyl Hydroxyhydrocinnamate, Sodium Hyaluronate, Oryza Sativa (Rice) Bran Extract, Propanediol, Jojoba Esters, Tocopherol, Acetyl Zingerone, Cetyl Palmitate, Caprylyl Glycol, Cetyl Alcohol, Polyglyceryl-3 Beeswax, Sodium Hydroxide, Sorbitan Olivate, Sorbitan Palmitate, Helianthus Annuus (Sunflower) Extract, Ethylhexylglycerin, Hexylene Glycol, Sodium Phytate, Polysorbate 60, Sorbitan Isostearate, Lecithin, Rosmarinus Officinalis (Rosemary) Leaf Extract, Glycine Soja (Soybean) Oil, Lysolecithin, Bacillus Ferment, Citric Acid, Polyglutamic Acid, Beta-Sitosterol, Phytic Acid, Squalene, Phenoxyethanol, Sodium Benzoate, Potassium Sorbate. IL331v3",
 category:"moisturizers",
},
{
 id:19,
 name:"DHC Deep Cleansing Oil 400ML",
 img:img2 ,
 description:"A hydrating, skin-nourishing cleanser.",
 price:16,
 overview:"DHC Deep Cleansing Oil removes excess oil, makeup, dirt and other pore-clogging impurities with its water-soluble formula. Infused with olive oil and vitamin E, it nourishes and hydrates the skin, while rinsing completely clean, never leaving behind a greasy residue.",
 use :"Remove the stopper attached to the pump. Dispense into dry hands, then massage onto dry face to dissolve makeup, dirt and other impurities. Rinse thoroughly.",
 ingredients:"Olea Europaea (Olive) Fruit Oil, Caprylic/Capric Triglyceride, Sorbeth-30 Tetraoleate, Pentylene Glycol, Phenoxyethanol, Tocopherol, Stearyl Glycyrrhetinate, Rosmarinus Officinalis (Rosemary) Leaf Oil.",
 category: "cleanser",
},
{
 id:20,
 name:"Caudalie Resveratrol-Lift Eye Firming Gel Cream",
 img:img18,
 description:"An eye cream to firm, smooth and redefine the delicate eye area.",
 price:62,
 overview:"Caudalie's Resveratrol-Lift Eye Firming Gel Cream addresses the signs of aging around the delicate eye area. This gel-cream is formulated with patented resveratrol, hyaluronic acid and a vegan collagen alternative to firm, depuff and reduce the look of wrinkles while peptides visibly smooth and redefine the eye contour area." ,
 use :"Apply morning and evening to eye and lip contours. Use with Resveratrol-Lift Instant Firming Serum for better results.",
 ingredients:"Aqua/Water/Eau, Butylene Glycol, Glycerin, Coco-Caprylate/Caprate, Isoamyl Laurate, Palmitoyl Grapevine Shoot Extract, Polyacrylate Crosspolymer-6, Ethylhexylglycerin, Sodium Polyacrylate, Stearyl Heptanoate, Sclerotium Gum, Xanthan Gum, Chenopodium Quinoa Seed Extract, Stearyl Caprylate, Tocopherol, Helianthus Annuus (Sunflower) Seed Oil, Benzyl Alcohol, Hydrolyzed Hyaluronic Acid, Caesalpinia Spinosa Fruit Extract, Adenosine, Acetyl Dipeptide-1 Cetyl Ester, Sodium Benzoate, Kappaphycus Alvarezii Extract, Sodium Phytate, Hyaluronic Acid, Khaya Senegalensis Bark Extract, Maltodextrin, Paeonia Lactiflora Root Extract.(259/009)",
 category:"eyecare",
},
{
 id:21,
 name:"NEOSTRATA Skin Active Intensive Eye Therapy Firming Cream for Mature Skin ",
 img:img19,
 description:"An anti-aging eye treatment that hydrates and smooths delicate skin.",
 price:86,
 overview:"NeoStrata's Intensive Eye Therapy lifts, tones, smooths, and hydrates your eye area. Peptides stimulate collagen production while hyaluronic acid hydrates and boosts smoother skin under the eyes. Caffeine promotes a more awakened look as it reduces puffiness." ,
 use :"Gently apply around the eye area until cream disappears. Use once daily for two weeks, then twice daily thereafter.",
 ingredients:"Aqua/Water/Eau, Dimethicone, Cyclopentasiloxane, Ploysilicone-11, Acetyl Glucosamine, Glycerin, Cyclohexasiloxane, Nylon-12, Silica, Octyldodecyl Stearate, Tocopheryl Acetate, Palmitoyl Tetrapeptide-7, Sodium Hyaluronate, Caffeine, Malus Domestica Fruit Cell Culture Extract, Butylene Glycol, Lecithin, Isohexadecane, PEG-10 Dimethicone, Caprylyl Glycol, Polysorbate 40, Sorbitan Isostearate, Polysorbate 60, Citric Acid, Hydroxyethyl Acrylate/Sodium Acryloyldimethyl Taurate Copolymer, Carbomer, Polysorbate 20, Isostearic Acid, Ammonium Polyacryloyldimethyl Taurate, Xanthan Gum, Chlorphenesin, Phenoxyethanol, Caramel, Yellow 5 (Cl 19140).",
 category:"eyecare",
},
{
 id:22,
 name:"La Roche-Posay Anthelios Ultra Light Fluid Face Sunscreen Broad Spectrum SPF 60",
 img:img20,
 description:"La Roche-Posay Anthelios Ultra Light Fluid Face Sunscreen Broad Spectrum SPF 60",
 price:33,
 overview:"La Roche-Posay's Anthelios Ultra Light Fluid Face Sunscreen Broad Spectrum SPF 60 provides broad-spectrum protection from the sun's harmful rays that may contribute to skin damage and premature aging of the skin. Lightweight and fast-absorbing, this facial sunscreen provides a non-whitening, matte finish and is formulated with Cell-Ox Shield® Technology and antioxidants to help visibly reduce the appearance of sun damage." ,
 use :"Apply 15 minutes before sun exposure, reapply every 2 hrs. For normal to combination skin. Water-resistant for up to 80 minutes.",
 ingredients:"Water, Cyclopentasiloxane, Alcohol Denat., Silica, Dicaprylyl Ether, Styrene/Acrylates Copolymer, Peg-30 Dipolyhydroxystearate, Dimethicone, Cyclohexasiloxane, Polymethylsilsesquioxane, Nylon-12, Dicaprylyl Carbonate, Diethylhexyl Syringylidenemalonate, Phenoxyethanol, Lauryl Peg/Ppg-18/18 Methicone, Sodium Chloride, Caprylyl Glycol, Peg-8 Laurate, Isostearyl Alcohol, Poly C 10-30 Alkyl Acrylate, Disteardimonium Hectorite, P-Anisic Acid, Caprylic/Capric Triglyceride, Disodium Edta, Cassia Alata Leaf Extract, Propylene Carbonate, Sodium Dodecylbenzenesulfonate, Tocopherol.",
 category:"spf",
},
]

export default data